### ISSUE TITLE
Instruction plz!

### ISSUE THREAD

**Issue by zombieQQ** [thanhlecongg/AlphaRepair#1]
thx for the code!Can you kindly provide some instructions to reproduce the experiments ? thanks a lot if you can help !!

**Comment by thanhlecongg** [comment]
Hi, this repo is actually implemented for the integration with [Cerberus](https://github.com/nus-apr/cerberus), you can use their instructions to run with option AlphaRepair. Note that, I am not the author of AlphaRepair so if you want to replicate the results from the paper, please refer to their original repo at Zenodo.

**Comment by thanhlecongg** [comment]
If you are interested in using the repo independently, please use this command:
```
python3 main.py --task repair 
--bug_id [ID of a bug, e.g., Chart-1]
--src_dir [/path/to/directory/of/source]
--buggy_file [buggy file, e.g., org.jfree.chart.renderer.category.AbstractCategoryItemRenderer]
--buggy_loc [location of the buggy line, e.g., 1797]
--re_rank 
--beam_width [with of beam, default of 25]
--top_n_patches [number of patches, default of 5000]
--output_folder [/path/to/output/folder]
```

To validate generated patches, please use this command:
```
python3 main.py --task validate 
--bug_id [ID of a bug, e.g., Chart-1]
--src_dir [/path/to/directory/of/source]
--buggy_file [buggy file, e.g., org.jfree.chart.renderer.category.AbstractCategoryItemRenderer]
--buggy_loc [location of the buggy line, e.g., 1797]
--output_folder [/path/to/output/folder]
```

If you want to use a Docker environment, please refer to thanhlecong/alpharepair:v1
Hope it help !!!
